### ISSUE TITLE
Use liferay-connector

### ISSUE THREAD

**Issue by yuchi** [drewbrokke/liferay-web-services-cli#2]
Great project! I had a similar idea for [liferay-connector](https://github.com/smclab/liferay-connector), which I suggest you to use for this project.

It’s a library which lets you to do the following (pardon my ES7):

``` js
// add-user.js

import liferay from 'liferay-connector';

export default async function addUser(userId, roleIds, cfg) {
  const session = await liferay.authenticate(cfg.portalURL, { login: cfg.login, password: cfg.password });
  return session.invoke({
    '/role/add-user-roles': {
      userId: userId,
      roleIds: roleIds
    }
  });
}
```

**Comment by drewbrokke** [comment]
Thanks @yuchi!  I like the suggestion, though it seems like it does not currently support development builds (I use the utility a lot for working on the master branch).  Is this configurable somehow?

```
err:  { [UnrecognizedLiferayVersion: Cannot recognize liferay version 7000]
  version: 7000,
  name: 'UnrecognizedLiferayVersion',
  message: 'Cannot recognize liferay version 7000' }
```

**Comment by yuchi** [comment]
The [current code](https://github.com/smclab/liferay-connector/blob/f6ad634120df61daf14566a12760df50685909fb/lib/connectors/liferay62.js#L68) is:

``` js
Liferay62.matches = function (buildnumber) {
  return buildnumber >= 6200 && buildnumber < 6300; // 7000
};
```

you can monkey patch it to:

``` js
import liferay from 'liferay-connector';
liferay.v62.matches = function (buildnumber) {
  return buildnumber >= 6200; // && buildnumber < 6300; // 7000
};
```

And it should work :smile:

**Comment by drewbrokke** [comment]
Thanks for the tip!  Looks like it does indeed work now :)  I'll take a look at what it would take to fully integrate the module.  I'm going to be doing some significant re-structuring to allow for a plugins architecture, so that may be a good opportunity to try this out.

For my own education, what are the primary advantages you see this tool gaining from the `liferay-connector` module?  I see there is significantly more compatibility checking for the connection than what I'm currently using, which I like :)

**Comment by yuchi** [comment]
1. Liferay Connector is cool and everyone should use it ( :P )
2. We’d be honored to see it used here
3. It’s compatible up to Liferay 6.1.1 GA2 :)
4. Its power comes from its error management and edge-case management (probably most of those are solved on master, didn’t yet checked)

**Comment by drewbrokke** [comment]
Can you give me an example of #4?  I certainly could use a broader perspective on potential use-cases that could break the tool

**Comment by yuchi** [comment]
- Liferay up to 6.2 mangles the expected parameter name, eg `displayDateLT` to `displayDateLt`
- service contexts passed as JSON don’t work
- errors must be [recognized by euheristics](https://github.com/smclab/liferay-connector/blob/f6ad634120df61daf14566a12760df50685909fb/lib/invoker.js#L96)

Those are the ones explicitly tested for. I’m pretty sure I missed some of them in the spec.

**Comment by drewbrokke** [comment]
Got it.  Thanks!  Also, I just tested using `liferay-connector` to add multiples (like you would with `lws add user 1000` or something similar), and it was _significantly_ faster than before, presumably because of the persistent session provided by the connector as opposed to hitting a url remotely every time.  That's nice to see :)

**Comment by yuchi** [comment]
Closing for obsolescence.
